AlistGo/docs

- docs/faq/why.md
- docs/zh/faq/why.md
- docs/zh/guide/webdav.md
尝试翻译了一下webdav.md，但是有些排版上的小问题自己并不是很清楚如何解决。
稍微修改了一下faq
此致
> add something

- docs/guide/drivers/115.md
- docs/guide/drivers/aliyundrive.md
- docs/zh/guide/drivers/115.md
- docs/zh/guide/drivers/aliyundrive.md
* 增加115网盘文档
* 由于跨域，以下两个二维码api需要文档网站做透明代理全转发并替换，参照阿里云盘的qrcode方式
* *  https://qrcodeapi.115.com/api/1.0/web/1.0/token
* *  https://qrcodeapi.115.com/get/status/
> add 115 driver doc

- docs/guide/install/docker.md
- docs/zh/guide/install/docker.md
> docker 安装文档更新

- docs/guide/install/docker.md
- docs/zh/guide/install/docker.md
1. Add docker-compose configuration
2. Add PUID and PGID configuration instructions
> document optimization

- docs/guide/README.md
- docs/zh/guide/README.md
> Fixed the `build` badge url

- docs/guide/install/docker.md
- docs/zh/guide/install/docker.md
> 增加docker-compose更新容器方式

- docs/.vuepress/components/google/Request.vue
- docs/guide/drivers/googlephotos.md
- docs/zh/guide/drivers/googlephotos.md
1. Fix typo and add more detail.
2. Fix `refresh_token` will not show more than once.
> (GooglePhotos) Fix typo and add more detail.

- docs/guide/drivers/baidu_share.md
- docs/zh/guide/drivers/baidu_share.md
Add an initial version of baidu_share.md
> feat: add baidu_share.md

- docs/guide/install/manual.md
- docs/zh/guide/install/manual.md
使用nssm配置Windows服务
如果有任何表述问题，特别是英文表述，可以直接修改
> 使用nssm配置Windows服务

- ecosystem.json
> 增加.net SDK

- docs/guide/drivers/googledrive.md
> docs: update a new method(service account) of use about google drive

- ecosystem.json
> update: ecosystem

- docs/guide/README.md
- docs/zh/guide/README.md
被官方松鼠发现我是热心用户，他们拜托我帮他们将文档的名字改为标识明显的官方名字。
> 修改UC网盘为官方的名字

- docs/guide/drivers/quark.md
- docs/zh/guide/drivers/quark.md
Reported at https://github.com/alist-org/alist/issues/4318#issuecomment-1837330284
Discussion can be seen at official Telegram group: https://t.me/alist_chat/638513
> docs: use firefox capture cookies may cause problem

- docs/guide/webdav.md
- docs/zh/guide/webdav.md
> webdav: Add MiXplorer on Android

- docs/config/preview.md
- docs/zh/config/preview.md
> Docs: add type query parameter usage for preview (src alist-org/alist-web#177)

- docs/guide/install/docker.md
- docs/zh/guide/install/docker.md
see: https://github.com/alist-org/alist/pull/6305
> docs: 添加部署时指定时区的方法说明

- docs/zh/guide/advanced/rapid_upload.md
> Fix: Fix misspelled column name

- docs/guide/drivers/Terabox.md
- docs/zh/guide/drivers/Terabox.md
目前文档中并没有 Terabox 的 jsToken 获取说明，现将获取说明添加进去了
> 添加了 Terabox(海外百度) 的 jsToken 获取说明

- docs/guide/advanced/offline-download.md
- docs/guide/drivers/115.md
- docs/zh/guide/advanced/offline-download.md
- docs/zh/guide/drivers/115.md
> docs(115): add offline download instructions

- docs/guide/install/paas.md
- docs/zh/guide/install/paas.md
> Add deploy on wekube

- docs/zh/guide/drivers/115.md
> Fix: word correction

- docs/zh/guide/drivers/115.md
详见 https://github.com/AlistGo/alist/discussions/7737
> docs(115): add 115ToAlist chrome extension

- docs/guide/api/admin/user.md
- docs/guide/api/auth.md
- docs/zh/guide/api/admin/user.md
- docs/zh/guide/api/auth.md
Document part of AlistGo/alist#7668
> docs(sftp-server): update docs
